### ISSUE TITLE
Localhost server is not working

### ISSUE THREAD

**Issue by pianimus** [andrewdavis33/sckernel#2]
Installation was completed as per the manual.
It works, but s.boot; could not do
This is displayed in the tk window.

Booting server 'localhost' on address 127.0.0.1:57110.
Server 'localhost' exited with exit code 1.

How can I solve this?
I definitely want to use it.

**Comment by andrewdavis33** [comment]
Can you tell me what operating system you are using?

It could be several things.  When you run `s.boot`, it launches an instance of scsynth, SuperCollider's server.  It likely is having an issue launching scsynth.  I assume running SuperCollider in the IDE works as expected.  I can give more precise things to check once I know what system you are using.

**Comment by pianimus** [comment]
I'm testing it on a windows 11 system.
The supercollider program works normally.
But I get a boot error in jupyter notebook.

**Comment by andrewdavis33** [comment]
I have seen this issue before.  The most likely culprit is again that sclang can't find the executable for the server.  Could be related to the issue documented here: https://github.com/supercollider/supercollider/issues/2719.  

Possible Solution: You'll need to modify your PATH environment variable in Windows.  Here is a quick link to how to do that if you haven't done it before: https://www.computerhope.com/issues/ch000549.htm.  Don't delete your current path.  Simply append to it.  The path should be the folder where scsynth.exe lives, typically the same folder as sclang.exe.  Give that a try and let me know if that works.

**Comment by pianimus** [comment]
> I have seen this issue before. The most likely culprit is again that sclang can't find the executable for the server. Could be related to the issue documented here: [supercollider/supercollider#2719](https://github.com/supercollider/supercollider/issues/2719).
> 
> Possible Solution: You'll need to modify your PATH environment variable in Windows. Here is a quick link to how to do that if you haven't done it before: https://www.computerhope.com/issues/ch000549.htm. Don't delete your current path. Simply append to it. The path should be the folder where scsynth.exe lives, typically the same folder as sclang.exe. Give that a try and let me know if that works.

Thanks!!   I've solved it. This worked just fine!!
